### ISSUE TITLE
[feature request] Make `devdocs-install` exclude already installed docs.

### ISSUE THREAD

**Issue by stardiviner** [astoff/devdocs.el#34]

**Comment by astoff** [comment]
If you call `devdocs-install` on an already installed document, it will be reinstalled / updated, which is an occasionally useful feature.

I understand why in a full-blown package manager you would like to have separate installation and update commands. But this is not a full-blown package manager... Can you explain why you want this feature?

**Comment by stardiviner** [comment]
Ok, I see, thanks for your explaination.

**Comment by defaultxr** [comment]
I would like this feature because it would be nice to be able to keep my `init.el` as declarative as possible, like what `use-package` allows, and I would prefer not to reinstall each doc that I want installed every time I start Emacs. That way, I can just copy my `init.el` to a new machine and everything I need is automatically installed without manual intervention on my part.

Unless I missed something, it seems devdocs doesn't support this use case at the moment, but I was able to hack a solution together:

```elisp
(defun devdocs-ensure-docs-installed (desired-docs)
  "Ensure that every devdoc listed in DESIRED-DOCS is installed, without reinstalling."
  (let ((installed (mapcar (lambda (installed-doc)
                             (cdr (assoc 'slug installed-doc)))
                           (devdocs--installed-docs))))
    (dolist (desired-doc desired-docs)
      (unless (cl-member desired-doc installed :test #'string=)
        (devdocs-install desired-doc)))))

(devdocs-ensure-docs-installed '(html css javascript))
```

**Comment by astoff** [comment]
That would be fine, but unless you want to eagerly load devdocs when Emacs starts, you should do
```
(with-eval-after-load 'devdocs 
  (devdocs-ensure-docs-installed '(html css javascript)))
```

**Comment by defaultxr** [comment]
I use `use-package`'s defer functionality for delaying package loads, but you're right that some users may prefer that method.
