### ISSUE TITLE
devdoc at point.

### ISSUE THREAD

**Issue by rileyrg** [astoff/devdocs.el#45]
Could the docs maybe include an example of calling this with (symbol-at-point) as the api to look up?`
I naively tried 

```
(devdocs-lookup nil (symbol-at-point))
```

**Comment by astoff** [comment]
You can of course define that command in your config, and I think it can be handy, but I would not add it to the package because reading from minibuffer with initial input is not the "normal" way to do things in Emacs.

Note also you can call `devdocs-lookup` then press `M-n` to insert the symbol at point (this "future historty" feature is the normal Emacs way to achieve that).
